# services:
#   fastapi:
#     build:
#       context: .
#       dockerfile: Dockerfile # Use the root Dockerfile
#     ports:
#       - "8000:8000"
#     command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

#   streamlit:
#     build:
#       context: .
#       dockerfile: Dockerfile # Use the root Dockerfile
#     ports:
#       - "8501:8501"
#     depends_on:
#       - fastapi
#     command:
#       [
#         "streamlit",
#         "run",
#         "streamlit/app.py",
#         "--server.port=8501",
#         "--server.address=0.0.0.0",
#       ]
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "8501:8501"
    environment:
      - API_URL=http://localhost:8000/separate_sota
